### PR TITLE
Update collabfunding.md

### PR DESCRIPTION
**Pull request by mdshearer**
Adding a small process change. Ops has now created a google form which triggers the start of the bucket payout process for us.
To come: Integration with a simple invoicing tool that'll generate invoices for people.

### CODE REVIEW

**Comment by rdbartlett** [comment]
Nice. 

1. can we make the form public access? I'm getting a permissions error which is such a pain because the new google forms UX gives me no option to switch accounts 😵 
2. you can link to the financial agreement like this `[Financial Agreement](financial_agreement.html)`. See if you can figure out how to update this pull request before I merge it :)

**Comment by mdshearer** [comment]
Oh. How curious, I guess I rushed that link...! I think I just committed a new link to this branch. Maybe...
Re: Form permissions. Ah yes, it was limiting to Enspiral. Can you test it now...?

**Comment by rdbartlett** [comment]
Bonza! Form is good now. It's a shame that Google Forms makes it hard to switch accounts.

Don't worry about it, but FYI it's slightly preferable to use relative links like `[Financial Agreement](financial_agreement.html)` rather than absolute links like `[Financial Agreement](http://handbook.enspiral.com/financial_agreement.html)`, because it means the links will still work even if we change domains, or say, someone clones the book to another location.

**Comment by mdshearer** [comment]
Oh cool, relative links is a thing! Thats handy and needs to be explained somewhere. Your first instruction I interpreted as shorthand for the absolute link rather than a tip about relative links. I've only ever come across relative/absolute in spreadsheet formula's.

And yes, Google form's can be annoyingly limited at times. Great for prototyping though.

**Pull request merged**
