### PR TITLE
[WIP, Don't merge, needs agreement] removing catalyst agreement and updating guide

### PR DESCRIPTION
**Pull request by joshuavial**
This is a suggestion that we remove the catalyst agreement and become just a working group focused on supporting people working to improve Enspiral.

### CODE REVIEW

**Comment by joshuavial** [comment]
I've removed all non trivial references to catalysts, the catalyst agreement itself and updated the page for the catalysts working group.

**Comment by rdbartlett** [comment]
👍

**Comment by joshuavial** [comment]
This build on gitbooks has the main additions https://handbook.enspiral.com/v/7e7629208168fe53308ea5cc506cf811ec193dac/working-groups/catalysts.html

**Comment by joshuavial** [comment]
closing in favour of the new catalyst agreement branch

**Pull request closed without merging**
