### PR TITLE
Update Cobudget invoice process.md

### PR DESCRIPTION
**Pull request by TheOtherPM**
Malcom suggested removing one part, so I've done that.

### CODE REVIEW

**Comment by rdbartlett** [comment]
I'm confused: @mdshearer I send that link to people all the time, why do you not want it in the handbook?

**Comment by mdshearer** [comment]
Not sure it's working right behind the scenes. We had some trouble getting the payment sorted for Paul. Keen to get it back out there in a couple more weeks.

**Comment by rdbartlett** [comment]
Ok good to know. Recently I shared the link with Paul and with Doris so you should see an invoice from her too. Should I follow up with her to tell her to email instead?

**Comment by rdbartlett** [comment]
p.s. this is exactly why it is good to use Pull Requests to manage edits to the handbook :)

**Pull request merged**
