### PR TITLE
ii handbook pipeline

### PR DESCRIPTION
**Pull request by hh**
# ii handbook pipeline

Inspired by Enspiral, ii wants to make it easy for groups to define who they are together.

Our pipeline creates a website per branch of each user for the handbook, so they can easily share a pdf or functioning website that includes their innovation without permission.

## Forking https://gitlab.ii.org.nz/enspiral/handbook

image

## Branching https://gitlab.ii.org.nz/ii/handbook/tree/manifesto

image

## Building https://gitlab.ii.org.nz/ii/handbook/pipelines/267

image

## Publishing https://gitlab.ii.org.nz/ii/handbook/builds/573

image

## Sharing http://manifesto.ii.handbook.ii.org.nz

image

### CODE REVIEW

**Comment by hh** [comment]
This might be of interest to you and is an example of how ii wants to partner with @enspiral
/cc @susanbasterfield @joshuavial

**Comment by rdbartlett** [comment]
ping @joshuavial

**Comment by joshuavial** [comment]
This is on my radar now @hh , I'll look at it this week - need to tweak my github mentions as they don't get through to my email.

**Comment by ckuiinz** [comment]
Updated CI config. Please refer to this version https://github.com/enspiral/handbook/pull/48

**Comment by hh** [comment]
https://gitlab.ii.org.nz/ii/handbook  commits result in a pdf and  website:

```docker run -p 80:80 -t http://docker.ii.org.nz/ii/handbook```

#default2open Thanks @enspiral

https://twitter.com/hippiehacker/status/772585240480985089

**Pull request merged**
