### PR TITLE
typo

### PR DESCRIPTION
**Pull request by agentlewis**
im guessing this is a typo - if not can someone explain why it is equity :)

### CODE REVIEW

**Comment by ahdinosaur** [comment]
not sure if typo but here's a cartoon :cat: 

[](http://interactioninstitute.org/illustrating-equality-vs-equity/)

**Comment by agentlewis** [comment]
[Oh interesting!](http://culturalorganizing.org/the-problem-with-that-equity-vs-equality-graphic/) I'm happy I learned this distinction.

@ahdinosaur do you think this is a common understanding? Or do you think we could possibly link to this article from [equity](http://culturalorganizing.org/the-problem-with-that-equity-vs-equality-graphic)

**Comment by rdbartlett** [comment]
I see your cartoon and raise you one anarchism:

image

**Comment by agentlewis** [comment]
closing the pr as its not needed

**Pull request closed without merging**
